feat: support cohort targeting for local evaluation
amplitude/experiment-ruby-server pull request #68
Opened 2024-07-23 23:23 UTC by tyiuhc

### Summary

Support cohort targeting for local evaluation 

### Checklist

* [X] Does your PR title have the correct [title format](https://github.com/amplitude/experiments-ruby-server/blob/main/CONTRIBUTING.md#pr-commit-title-conventions)?
* Does your PR have a breaking change?:   No

2024-08-05 20:24 UTC, bgiori requested changes
We should make it so that any use of the cohort loader goes through the load_cohort function.

2024-08-05 20:24 UTC, bgiori commented on lib/experiment/cohort/cohort_loader.rb
> +    def update_stored_cohorts
Can we remove this function and just call load_cohort for each cohort stored in storage instead?

2024-08-05 20:24 UTC, bgiori commented on lib/experiment/cohort/cohort_sync_config.rb
> +    #     cohort_request_delay_millis (int): The delay in milliseconds between cohort download requests
I would specify that this delay is only applied on failure.

2024-08-05 20:24 UTC, bgiori commented on lib/experiment/cohort/cohort_loader.rb
> +          errors << result if result.is_a?(Array) && result[1].is_a?(StandardError)
`[1]`?

2024-08-05 20:24 UTC, bgiori commented on lib/experiment/deployment/deployment_runner.rb
> +          flag_config = flag_config[1]
What does the `[1]` do?

2024-08-05 20:24 UTC, bgiori commented on lib/experiment/deployment/deployment_runner.rb
> +          @logger.warn("Download cohort #{cohort_id} failed: #{reason}")
probably want to do an error log

2024-08-08 20:01 UTC, bgiori approved these changes

2024-08-08 20:27 UTC, zhukaihan approved these changes

2024-08-27 16:25 UTC, merged